### ISSUE TITLE
After the picture is put in, it starts to run. I don't know what the problem is

### ISSUE THREAD

**Issue by DDDXXXUFO** [natethegreate/Screentone-Remover#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1558, in __call__
  File "stremove.py", line 222, in <lambda>
  File "stremove.py", line 135, in removeScreentones
  File "stremove.py", line 25, in blur
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:757: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'

**Comment by DDDXXXUFO** [comment]
I put five black and white cartoons, the sharpening value is the default (I don't adjust anything), and then input the location (package/input_images) and output (package/output). As a result, I ran the stremove.exe file and these errors occurred
